import { getContentfulData } from "@/lib/methods"
import Preloader from "@/redux/Preloader"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  // fetches content from contentful from the collection for PixelPapers
  const content = await getContentfulData()

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <preloader/> syncs server side redux store to client side store */}
      <Preloader
        data={{
          content,
        }}
      />
    </html>
  )
}

export default RootLayout
