import Preloader from "@/redux/Preloader"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <preloader/> syncs server side redux store to client side store */}
      <Preloader
        data={{
          count: 10,
        }}
      />
    </html>
  )
}
