export const GLOBAL_COLORS = {
  TEXT_PRIMARY_DARK: "#222",
  TEXT_PRIMARY_LIGHTER: "#555",
  TEXT_PRIMARY_LIGHT: "#d9d9d9",
  BACKGROUND_PRIMARY_LIGHT: "#fefefe",
  BACKGROUND_PRIMARY_DARK: "#111",
}

export const PAGE_LEVEL_COLORS = {
  TRAVEL: {
    BACKGROUND_PRIMARY_LIGHT: "#ffe2e2",
    BACKGROUND_PRIMARY_DARK: "#ff0000",
    TEXT_PRIMARY_LIGHTER: "#444",
  },
}
